### ISSUE TITLE
dependency list of boost::hana should be smaller (almost empty)

### ISSUE THREAD

**Issue by burnpanck** [iceboy233/boost#16]
The dependencies for `hana` contain `mpl` and `fusion` among others. Both of them are heavy libraries. However, `hana` itself is fully standalone and perfectly usable without any of the other boost libraries (except for maybe `config` in the boost variant of the library). It is true that `hana` provides interoperability with `mpl` and `fusion`, and for that interoperability, of course you need those libraries as-well. However, I believe it should be the users choice of pulling in those libraries *if* they actually want to use them.

**Comment by iceboy233** [comment]
Thanks for bringing this up. How does https://github.com/iceboy233/boost/pull/17 look?

**Comment by burnpanck** [comment]
Looks good to me, thanks for the quick response!
